[build]
  command = "echo ready"
  publish = "."

[[redirects]]
  from = "/audio/*"
  to = "/.netlify/functions/audio-proxy?song_id=:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "https://github.com/XiOuDi/163music-netlify-proxy"
  status = 302

[functions]
  directory = "netlify/functions"
